# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Firebase App Distribution"
  lane :firebase_distribution do
    # sh "flutter clean"
    # sh "flutter build apk --flavor Production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:730709367532:android:bda1d9a722c34c8aaa23c9",
    firebase_cli_token: "1//036KEe0i0utF9CgYIARAAGAMSNgF-L9IrKbJw8smIjoSSWEyUe0ydiZmNNlxogOCxjU6N2K6VgWisZrn0FMxGs6xjAQSocwytGA",
    # service_credentials_file: "fastlane/service-account-key.json",
    android_artifact_type: "APK",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "omarhan113355@gmail.com",
    release_notes: "First FastLane Firebase ",
    debug: true,
    upload_timeout: 1200
  )
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end


